=== DonMostro/play-xml/ls/components/components.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT component (element*,tab*)>
<!ATTLIST component
	name CDATA #IMPLIED
	type (table | table_dojo | settings | settings_dojo | php_info | curl_dojo) #REQUIRED
	excel (true | false) #IMPLIED
	change_password (true | false) #IMPLIED
	functions CDATA #IMPLIED  
	functions_permissions (list | add | edit | delete) #IMPLIED
	table_dojo_type (dojox.grid.EnhancedGrid) #IMPLIED
	plugins CDATA #IMPLIED
	id CDATA #IMPLIED
	target CDATA #IMPLIED
	search CDATA #IMPLIED
	search_type CDATA #IMPLIED
	search_dojo_type CDATA #IMPLIED 
	search_invalid_message CDATA #IMPLIED
	search_prompt_message CDATA #IMPLIED
	search_table CDATA #IMPLIED
	search_table_element CDATA #IMPLIED
	search_table_target CDATA #IMPLIED
	search_table_field CDATA #IMPLIED
	search_display CDATA #IMPLIED	
	search_additional_validation (true) #IMPLIED
	edit_additional_validation (true) #IMPLIED
	links CDATA #IMPLIED
	popups CDATA #IMPLIED
	popups_title CDATA #IMPLIED
	js  CDATA #IMPLIED
	list (true | false) #IMPLIED
	edit (true | false) #IMPLIED
	add (true | false) #IMPLIED
	delete (true | false) #IMPLIED
>
<!ELEMENT element (#PCDATA)>
<!ATTLIST element 
	name CDATA #IMPLIED
	type (null | checkbox | dojo_combo_box | dojo_calendar | dojo_filtering_select | dojo_validation_textbox | dojo_checkbox | id_box | password | select | textarea | textelement | xml_list | yes_no | dojo_yes_no | element | permissions_modules | dojo_textarea | dojo_validation_textarea | hidden) #REQUIRED
	target CDATA #IMPLIED
	trim (true | false) #IMPLIED
	reg_exp CDATA #IMPLIED
	required (true | false) "true"
	visible (true | false) "true"
	edit (true | false) "false"
	add (true | false) "false"
	table CDATA #IMPLIED
	field  CDATA #IMPLIED
	table_pk CDATA #IMPLIED
	table_method CDATA #IMPLIED
	table_element CDATA #IMPLIED
	table_field CDATA #IMPLIED
	default_value CDATA #IMPLIED
	default_text CDATA #IMPLIED
	element CDATA #IMPLIED	
	image CDATA #IMPLIED
	link CDATA #IMPLIED
	list CDATA #IMPLIED
	default CDATA #IMPLIED
	value CDATA #IMPLIED
	constraints CDATA #IMPLIED 
	search_format CDATA #IMPLIED
	search_required CDATA #IMPLIED
	search_constraints CDATA #IMPLIED
	search_reg_exp CDATA #IMPLIED 	
	invalid_message CDATA #IMPLIED
	prompt_message CDATA #IMPLIED
	onchange CDATA #IMPLIED
	onblur CDATA #IMPLIED 
	disabled CDATA #IMPLIED	
	offset CDATA #IMPLIED
	checked CDATA #IMPLIED
	formatter CDATA #IMPLIED
	maxlength CDATA #IMPLIED
	join CDATA #IMPLIED
	clone (true | false) #IMPLIED			 			
>
<!ELEMENT tab (element*)>
<!ATTLIST tab
	name CDATA #IMPLIED
	target CDATA #IMPLIED
	id CDATA #IMPLIED
	add (true | false) #IMPLIED	
	edit (true | false) #IMPLIED	
	clone (true | false) #IMPLIED	
>

=== DonMostro/play-xml/ls/components/recursos.xml
<?xml version="1.0"?>
<!DOCTYPE component PUBLIC "//COMPONENTS/" "components.dtd">
<component name="Recurso" type="table_dojo" target="recursos" search="false" list="true" edit="true" add="true" delete="true">
    <element name="ID" target="id" type="id_box" visible="true" edit="false" add="false"/>
    <element name="Categor&amp;iacute;a" target="categoria_id" type="dojo_filtering_select" table="categoria" field="categoria" table_method="get_categorias"  visible="true" edit="true" add="true"/>    
    <element name="C&amp;oacute;digo" target="codigo" reg_exp="[\d]+" invalid_message="Solo números" type="dojo_validation_textbox" visible="true" edit="true" add="true"/>
    <element name="Nombre" target="nombre" type="dojo_validation_textbox" visible="true" edit="true" add="true"/>
    <element name="Descripci&amp;oacute;n" target="descripcion" type="dojo_validation_textbox" visible="true" edit="true" add="true"/>    
    <element name="Posici&amp;oacute;n" target="posicion" reg_exp="[\d]+" invalid_message="Solo números" type="dojo_validation_textbox" visible="true" edit="true" add="true"/>    
    <element name="Estado" target="estado" reg_exp="[\d]+" invalid_message="Solo números" type="dojo_validation_textbox" visible="true" edit="true" add="true"/>
    <element name="" target="" type="element" default="Items" link="components?p=items&amp;recursos_id={id}" visible="true" edit="false" add="false"/>
    <element name="" target="" type="element" default="Variables" link="components?p=variables&amp;recursos_id={id}" visible="true" edit="false" add="false"/>       
</component>
